version: "3.8"

services:
  data-reader-service:
    build:
      context: ./data-reader
      dockerfile: DockerfileDataReader
    networks:
      microservice-network:
        aliases:
          - data-reader-service

  compute-service:
    build:
      context: ./compute
      dockerfile: DockerfileCompute
    networks:
      microservice-network:
        aliases:
          - compute-service
    depends_on:
      - data-reader-service

  result-formatter-service:
    build:
      context: ./result-formatter
      dockerfile: DockerfileFormatter
    networks:
      microservice-network:
        aliases:
          - result-formatter-service
    depends_on:
      - compute-service
    ports:
      - "8000:8082"

networks:
  microservice-network:
    driver: bridge
