version: "3.8"

services:
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"

  reader:
    build: 
      context: ./ 
      dockerfile: ./Dockerfile/Dockerfile_readerService
    volumes:
        - ./data:/app/data
    networks:
      - microservice-network

  compute:
    build: 
      context: ./
      dockerfile: ./Dockerfile/Dockerfile_computeService
    networks:
      - microservice-network

  ochestrator:
    build: 
      context: ./
      dockerfile: ./Dockerfile/Dockerfile_orchestratorService
    ports:
      - "8000:8000"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
